import Head from "next/head";
import Image from "next/image";
import Nav from "@/components/Nav";
import Footer from "@/components/footer";
import { Inter } from "next/font/google";
import Posts from "@/components/posts";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });


import { MongoClient } from "mongodb";

const uri = process.env.DB_PASS;

export async function getServerSideProps() {
    const client = new MongoClient(uri);
    let posts = []
    try {
      await client.connect();
      const db = client.db("posts");
   
      const category = db.collection('Stories');
      posts = await category.find({},{projection:{_id:0,postBody:0}}).sort({_id: -1}).toArray();
      console.log(posts)

    } catch (e) {
      console.log(e)
    } finally {
      await client.close();
    }
    return {
      props: {
       posts
      },
    };
}


export default function Stories({posts}) {
  return (
    <>
      <Head>
        <title>Stories | Chuksjohnleo Blogs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <Nav path={"Stories"} />
      <h1>Stories Category</h1>
      <main className={styles.main}>
        <div className={styles.description}>
          <h2>
            Hello, This is News I appreciate your I appreciate your coming. loremI appreciate
           oming. lorem welcome to my blog
          </h2>
        </div>
        <section className={styles.posts}>
        <div>          
           {posts.map(post=>{
            return <div key={post.id}><Posts post={post} /></div>
           })}
        </div>
        </section>
      </main>
      <Footer />
    </>
  );
}