import React, { useEffect, useState } from "react";
import Nav from "@/components/Nav";
import Footer from "@/components/footer";
import Head from "next/head";
import utilStyle from '@/styles/utils.module.css';
import styles from "@/styles/Notification.module.css";
import NotificationNav from "@/components/notificationNav";

export default function Notifications() {

  return (
    <>
      <Head>
        <title>Notifications | Chuksjohnleo Blogs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <Nav path={"Notifications"} majorPath={"Notifications"} ProperNav={NotificationNav} />
      <main className={styles.main}>
        <section>
          <div>Notification one</div>
          <div>Notification two</div>
          <div>Notification three</div>
          <div>Notification four</div>
        </section>
      </main>
      <Footer/>
    </>
  );
}
